# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ad6cec97ee8af5dc83613f9697272d222f860644a573a0075d82f832e3762821f7ab8f17075b129662194a91843000c2c5f25e152a70c8f0ce9b5c28499b0b4

test:
  secret_key_base: 93a7374378c80391d66f7438586bafe21edaa7af7dab6faafb58d741cd4e9fbc182ddbcae982550e30ce8738b0fd8ea34cdc790d434c2b4cc3cbe32c7f3acb27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
